// <auto-generated />
namespace Todo_Asp_Mvc.Net.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_properties_tables_constraints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_properties_tables_constraints));
        
        string IMigrationMetadata.Id
        {
            get { return "202307181307213_add_properties_tables_constraints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
